export type SettingInfo = {
  name: string
  description: string
  type: 'string' | 'number' | 'boolean' | 'enum'
  defaultValue: string | number | boolean
  sourceFile: 'GameUserSettings.ini' | 'Game.ini'
  sourceSection?: string
}

export type IniFileName = 'GameUserSettings.ini' | 'Game.ini'

export const getSettingInfo = (
  key: string,
  registry: Record<string, SettingInfo>,
): SettingInfo | undefined => {
  const displayLabel = key.includes('.') ? key.split('.').pop() ?? key : key
  const lookupKey = displayLabel.replace(/\[\d+\]$/, '')

  return (
    registry[displayLabel] ??
    registry[lookupKey] ??
    Object.entries(registry).find(([settingName]) =>
      settingName.toLowerCase() === displayLabel.toLowerCase() ||
      settingName.toLowerCase() === lookupKey.toLowerCase(),
    )?.[1]
  )
}

export const userSettingsIniSettingsInfo: Record<string, SettingInfo> = {
  ServerCrosshair: {
    name: 'ServerCrosshair',
    description: 'Shows the server crosshair in the client UI when enabled.',
    type: 'boolean',
    defaultValue: true,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  AllowThirdPersonPlayer: {
    name: 'AllowThirdPersonPlayer',
    description: 'Allows third-person player camera usage on the server when enabled.',
    type: 'boolean',
    defaultValue: true,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  ServerPVE: {
    name: 'ServerPVE',
    description: 'Turns PvE mode on for the server when enabled.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  serverPVE: {
    name: 'serverPVE',
    description: 'Alternate lowercase PvE flag used by some server configs.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  ServerHardcore: {
    name: 'ServerHardcore',
    description: 'Enables hardcore mode for players when turned on.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  ServerPassword: {
    name: 'ServerPassword',
    description: 'Requires players to provide a password before joining the server.',
    type: 'string',
    defaultValue: '',
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  ServerAdminPassword: {
    name: 'ServerAdminPassword',
    description: 'Sets the password required to access admin commands on the server.',
    type: 'string',
    defaultValue: '',
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  DayCycleSpeedScale: {
    name: 'DayCycleSpeedScale',
    description: 'Controls how quickly the in-game day cycle progresses.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  DayTimeSpeedScale: {
    name: 'DayTimeSpeedScale',
    description: 'Sets the speed of daytime progression relative to nighttime.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  NightTimeSpeedScale: {
    name: 'NightTimeSpeedScale',
    description: 'Sets the speed of nighttime progression relative to daytime.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  DifficultyOffset: {
    name: 'DifficultyOffset',
    description: 'Adjusts the server difficulty offset from the default setting.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  OverrideOfficialDifficulty: {
    name: 'OverrideOfficialDifficulty',
    description: 'Overrides the official difficulty preset used by the server.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  XPMultiplier: {
    name: 'XPMultiplier',
    description: 'Scales the amount of XP gained from gameplay actions.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  HarvestAmountMultiplier: {
    name: 'HarvestAmountMultiplier',
    description: 'Scales the yield from harvesting and resource collection.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  TamingSpeedMultiplier: {
    name: 'TamingSpeedMultiplier',
    description: 'Scales how quickly creatures can be tamed.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  PlayerDamageMultiplier: {
    name: 'PlayerDamageMultiplier',
    description: 'Scales the damage dealt by player characters.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  PlayerResistanceMultiplier: {
    name: 'PlayerResistanceMultiplier',
    description: 'Scales the resistance of player characters to incoming damage.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  DinoDamageMultiplier: {
    name: 'DinoDamageMultiplier',
    description: 'Scales the damage dealt by wild creatures.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  DinoResistanceMultiplier: {
    name: 'DinoResistanceMultiplier',
    description: 'Scales the resistance of wild creatures to incoming damage.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  StructureDamageMultiplier: {
    name: 'StructureDamageMultiplier',
    description: 'Scales the damage dealt by structures such as spike walls.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  StructureResistanceMultiplier: {
    name: 'StructureResistanceMultiplier',
    description: 'Scales the resistance of structures to incoming damage.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  MaxPlayers: {
    name: 'MaxPlayers',
    description: 'Sets the maximum number of players that can join the server session.',
    type: 'number',
    defaultValue: 70,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[/Script/Engine.GameSession]',
  },
  Port: {
    name: 'Port',
    description: 'Sets the game port used by the dedicated server.',
    type: 'number',
    defaultValue: 7777,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[SessionSettings]',
  },
  QueryPort: {
    name: 'QueryPort',
    description: 'Sets the query port used by Steam server browser discovery.',
    type: 'number',
    defaultValue: 27015,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[SessionSettings]',
  },
  SessionName: {
    name: 'SessionName',
    description: 'Defines the server name that appears in the server browser.',
    type: 'string',
    defaultValue: 'ARK #123456',
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[SessionSettings]',
  },
  MultiHome: {
    name: 'MultiHome',
    description: 'Sets the bind IP for multihome server setups.',
    type: 'string',
    defaultValue: '',
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[MultiHome]',
  },
  RCONEnabled: {
    name: 'RCONEnabled',
    description: 'Enables remote console access for the server when turned on.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  RCONPort: {
    name: 'RCONPort',
    description: 'Sets the TCP port used for remote console access.',
    type: 'number',
    defaultValue: 27020,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[ServerSettings]',
  },
  Duration: {
    name: 'Duration',
    description: 'Sets how long the welcome message remains visible after login.',
    type: 'number',
    defaultValue: 20,
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[MessageOfTheDay]',
  },
  Message: {
    name: 'Message',
    description: 'Defines the message shown to players when they log in.',
    type: 'string',
    defaultValue: '',
    sourceFile: 'GameUserSettings.ini',
    sourceSection: '[MessageOfTheDay]',
  },
}

export const gameIniSettingsInfo: Record<string, SettingInfo> = {
  PerLevelStatsMultiplier_DinoTamed: {
    name: 'PerLevelStatsMultiplier_DinoTamed',
    description: 'Controls the per-level stat gain curve for tamed dinosaurs. The wiki lists defaults such as 0.2 for health and 0.17 for damage for the base tamed curve.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  PerLevelStatsMultiplier_DinoTamed_Add: {
    name: 'PerLevelStatsMultiplier_DinoTamed_Add',
    description: 'Applies the additive per-level stat multiplier for tamed dinosaurs, which is used for the immediate stat gain added at each level-up.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  PerLevelStatsMultiplier_DinoTamed_Affinity: {
    name: 'PerLevelStatsMultiplier_DinoTamed_Affinity',
    description: 'Applies the affinity-dependent per-level stat multiplier for tamed dinosaurs, which scales stat gains based on affinity.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  PerLevelStatsMultiplier_DinoWild: {
    name: 'PerLevelStatsMultiplier_DinoWild',
    description: 'Controls the per-level stat gain curve for wild dinosaurs. The wiki lists the default wild curve as 1.0 for most stats.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  PerLevelStatsMultiplier_Player: {
    name: 'PerLevelStatsMultiplier_Player',
    description: 'Controls the per-level stat gain curve for players. For example, PerLevelStatsMultiplier_Player[7]=2.0 doubles the weight gain per level.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  NPCReplacements: {
    name: 'NPCReplacements',
    description: 'Used to replace or disable creature spawns by swapping one creature blueprint for another. To disable a spawn, leave the replacement target blank or zero out the spawn weight in the spawn-entry config.',
    type: 'string',
    defaultValue: '',
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  ConfigOverrideNPCSpawnEntriesContainer: {
    name: 'ConfigOverrideNPCSpawnEntriesContainer',
    description: 'Overrides a spawn container with a custom list of spawn entries, commonly used to replace or disable specific dino spawns for a region or map.',
    type: 'string',
    defaultValue: '',
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  ConfigAddNPCSpawnEntriesContainer: {
    name: 'ConfigAddNPCSpawnEntriesContainer',
    description: 'Adds extra spawn entries to an existing container, which can be used to introduce replacements or alternate spawns alongside the default list.',
    type: 'string',
    defaultValue: '',
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  NPCSpawnEntriesContainerClassString: {
    name: 'NPCSpawnEntriesContainerClassString',
    description: 'Names the spawn container class that the spawn-entry overrides or additions should target.',
    type: 'string',
    defaultValue: '',
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  NPCSpawnEntries: {
    name: 'NPCSpawnEntries',
    description: 'Defines the spawn-entry list for a container. Each entry can point at a creature blueprint and an entry weight that controls spawn likelihood.',
    type: 'string',
    defaultValue: '',
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  EntryName: {
    name: 'EntryName',
    description: 'Names the creature or spawn entry being overridden or added. This is the value you swap when replacing one dino spawn with another.',
    type: 'string',
    defaultValue: '',
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  EntryWeight: {
    name: 'EntryWeight',
    description: 'Controls how likely a spawn entry is to appear. Setting it to 0 effectively disables that spawn entry in the container.',
    type: 'number',
    defaultValue: 0,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  BabyImprintingStatScaleMultiplier: {
    name: 'BabyImprintingStatScaleMultiplier',
    description: 'Scales how much imprinting quality affects baby stats.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  BabyMatureSpeedMultiplier: {
    name: 'BabyMatureSpeedMultiplier',
    description: 'Scales the maturation speed of babies and juveniles.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bAllowFlyerSpeedLeveling: {
    name: 'bAllowFlyerSpeedLeveling',
    description: 'Allows flyers to gain movement speed levels when enabled.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bAllowSpeedLeveling: {
    name: 'bAllowSpeedLeveling',
    description: 'Allows players and non-flyers to gain movement speed levels.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bAllowUnlimitedRespecs: {
    name: 'bAllowUnlimitedRespecs',
    description: 'Removes the normal cooldown when reusing Mindwipe Tonic respecs.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bAutoPvETimer: {
    name: 'bAutoPvETimer',
    description: 'Enables automatic PvE mode scheduling on PvPvE servers.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bAutoPvEUseSystemTime: {
    name: 'bAutoPvEUseSystemTime',
    description: 'Uses the server system clock instead of in-game time for auto PvE toggling.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  AutoPvEStartTimeSeconds: {
    name: 'AutoPvEStartTimeSeconds',
    description: 'Sets the in-game time when automatic PvE mode begins.',
    type: 'number',
    defaultValue: 0,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  AutoPvEStopTimeSeconds: {
    name: 'AutoPvEStopTimeSeconds',
    description: 'Sets the in-game time when automatic PvE mode ends.',
    type: 'number',
    defaultValue: 0,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bDisableDinoTaming: {
    name: 'bDisableDinoTaming',
    description: 'Prevents players from taming creatures when enabled.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bDisableFriendlyFire: {
    name: 'bDisableFriendlyFire',
    description: 'Stops friendly-fire damage between allied players and creatures.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bDisablePhotoMode: {
    name: 'bDisablePhotoMode',
    description: 'Disables photo mode when enabled.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bDisableStructurePlacementCollision: {
    name: 'bDisableStructurePlacementCollision',
    description: 'Allows structures to clip into terrain when enabled.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bUseCorpseLocator: {
    name: 'bUseCorpseLocator',
    description: 'Enables the corpse locator beacon when enabled.',
    type: 'boolean',
    defaultValue: true,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bAutoUnlockAllEngrams: {
    name: 'bAutoUnlockAllEngrams',
    description: 'Unlocks all available engrams automatically when enabled.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bAllowCustomRecipes: {
    name: 'bAllowCustomRecipes',
    description: 'Allows custom recipes to be used when enabled.',
    type: 'boolean',
    defaultValue: true,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bAllowPlatformSaddleMultiFloors: {
    name: 'bAllowPlatformSaddleMultiFloors',
    description: 'Allows platform saddles to span multiple floors when enabled.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bIncreasePvPRespawnInterval: {
    name: 'bIncreasePvPRespawnInterval',
    description: 'Extends PvP respawn delays when enabled.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  IncreasePvPRespawnIntervalBaseAmount: {
    name: 'IncreasePvPRespawnIntervalBaseAmount',
    description: 'Sets the base amount of extra PvP respawn delay.',
    type: 'number',
    defaultValue: 60,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  IncreasePvPRespawnIntervalCheckPeriod: {
    name: 'IncreasePvPRespawnIntervalCheckPeriod',
    description: 'Sets how often the PvP respawn interval is checked.',
    type: 'number',
    defaultValue: 300,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  IncreasePvPRespawnIntervalMultiplier: {
    name: 'IncreasePvPRespawnIntervalMultiplier',
    description: 'Scales the added PvP respawn delay when the modifier is active.',
    type: 'number',
    defaultValue: 2,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bPassiveDefensesDamageRiderlessDinos: {
    name: 'bPassiveDefensesDamageRiderlessDinos',
    description: 'Allows passive defenses to damage riderless creatures when enabled.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bPvEAllowTribeWar: {
    name: 'bPvEAllowTribeWar',
    description: 'Allows tribes to declare war on each other in PvE when enabled.',
    type: 'boolean',
    defaultValue: true,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bPvEAllowTribeWarCancel: {
    name: 'bPvEAllowTribeWarCancel',
    description: 'Allows tribe wars to be canceled before they begin in PvE.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bShowCreativeMode: {
    name: 'bShowCreativeMode',
    description: 'Adds a creative mode toggle to the pause menu when enabled.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  bUseSingleplayerSettings: {
    name: 'bUseSingleplayerSettings',
    description: 'Applies single-player balancing presets when enabled.',
    type: 'boolean',
    defaultValue: false,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  DinoTurretDamageMultiplier: {
    name: 'DinoTurretDamageMultiplier',
    description: 'Scales the damage dealt by automated dinosaur turrets.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  FishingLootQualityMultiplier: {
    name: 'FishingLootQualityMultiplier',
    description: 'Scales the quality of loot produced by fishing activities.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  FuelConsumptionIntervalMultiplier: {
    name: 'FuelConsumptionIntervalMultiplier',
    description: 'Changes how often fuel-consuming devices consume fuel.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  GlobalCorpseDecompositionTimeMultiplier: {
    name: 'GlobalCorpseDecompositionTimeMultiplier',
    description: 'Scales how long corpses remain before they decompose.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  GlobalItemDecompositionTimeMultiplier: {
    name: 'GlobalItemDecompositionTimeMultiplier',
    description: 'Scales how long dropped items remain before they decompose.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
  GlobalSpoilingTimeMultiplier: {
    name: 'GlobalSpoilingTimeMultiplier',
    description: 'Scales the rate at which perishables spoil across the world.',
    type: 'number',
    defaultValue: 1,
    sourceFile: 'Game.ini',
    sourceSection: '[/Script/ShooterGame.ShooterGameMode]',
  },
}
