;METADATA=(Diff=true, UseCommands=true)
[ServerSettings]
DifficultyOffset=1.0
OverrideOfficialDifficulty=4.1
DayCycleSpeedScale=1.0
DayTimeSpeedScale=1.0
NightTimeSpeedScale=2.5
DinoDamageMultiplier=1.0
PlayerDamageMultiplier=1.8
StructureDamageMultiplier=1.0
PlayerResistanceMultiplier=1.0
DinoResistanceMultiplier=1.0
StructureResistanceMultiplier=0.2
XPMultiplier=1.8
TamingSpeedMultiplier=7
HarvestAmountMultiplier=1.8
PlayerCharacterWaterDrainMultiplier=0.4
PlayerCharacterFoodDrainMultiplier=0.4
DinoCharacterFoodDrainMultiplier=1.3
PlayerCharacterStaminaDrainMultiplier=0.2
DinoCharacterStaminaDrainMultiplier=0.2
PlayerCharacterHealthRecoveryMultiplier=2
DinoCharacterHealthRecoveryMultiplier=2
HarvestHealthMultiplier=2
PvEStructureDecayPeriodMultiplier=1.0
ResourcesRespawnPeriodMultiplier=0.5
StartTimeOverride=False
StartTimeHour=0.3
RaidDinoCharacterFoodDrainMultiplier=1.0
StructurePreventResourceRadiusMultiplier=1.0
PvEDinoDecayPeriodMultiplier=1.0
AllowRaidDinoFeeding=True
PerPlatformMaxStructuresMultiplier=2
GlobalVoiceChat=False
ProximityChat=False
NoTributeDownloads=False
AllowThirdPersonPlayer=True
AlwaysNotifyPlayerLeft=False
DontAlwaysNotifyPlayerJoined=False
ServerHardcore=False
ServerPVE=True
ServerCrosshair=True
ServerForceNoHUD=False
ShowMapPlayerLocation=True
EnablePvPGamma=True
DisableStructureDecayPvE=True
AllowFlyerCarryPvE=True
OnlyAllowSpecifiedEngrams=False
AllowHideDamageSourceFromLogs=True
RandomSupplyCratePoints=False
DisableWeatherFog=False
PreventDownloadSurvivors=False
PreventDownloadItems=False
PreventDownloadDinos=False
DisablePvEGamma=False
DisableDinoDecayPvE=False
AdminLogging=False
AllowCaveBuildingPvE=True
ForceAllowCaveFlyers=True
PreventOfflinePvP=False
PvPDinoDecay=False
OverrideStructurePlatformPrevention=True
AllowAnyoneBabyImprintCuddle=True
DisableImprintDinoBuff=False
ForceResetWildDinos=False
ShowFloatingDamageText=True
PreventDiseases=True
NonPermanentDiseases=False
EnableExtraStructurePreventionVolumes=False
PreventTribeAlliances=False
bAllowSpeedLeveling=False
bAllowFlyerSpeedLeveling=False
PreventOfflinePvPInterval=0
CraftingSkillBonusMultiplier=1.5
SupplyCrateLootQualityMultiplier=1.5
ActiveEvent=None
OverrideStartTime=False
ForceGachaUnhappyInCaves=False
ActiveMods=
ActiveMapMod=0
ServerPassword=Password
ServerAdminPassword=Password
NeedsPowerToActivateAquaticCompartments=True
RCONPort=27020
TheMaxStructuresInRange=10500
OxygenSwimSpeedStatMultiplier=1
TribeNameChangeCooldown=15
PlatformSaddleBuildAreaBoundsMultiplier=2
AlwaysAllowStructurePickup=True
StructurePickupTimeAfterPlacement=30
StructurePickupHoldDuration=0.5
KickIdlePlayersPeriod=3600
AutoSavePeriodMinutes=15
MaxTamedDinos=5000
MaxTamedDinos_SoftTameLimit=5000
MaxTamedDinos_SoftTameLimit_CountdownForDeletionDuration=604800
OverrideSecondsUntilBuriedTreasureAutoReveals=1209600
ItemStackSizeMultiplier=1.5
RCONServerGameLogBuffer=600
ImplantSuicideCD=28800
AllowHitMarkers=True
LimitBunkersPerTribe=True
LimitBunkersPerTribeNum=3
AllowRidingDinosInsideBunkers=True
AllowDinoAIInsideBunkers=True
MinDistanceBetweenBunkers=3000
EnemyAccessBunkerHPThreshold=0.2
BunkerUnderHPThresholdDmgMultiplier=0.1
CryoHospitalHoursToRegenHP=1
CryoHospitalHoursToRegenFood=24
CryoHospitalHoursToDrainTorpor=1
CryoHospitalMatingCooldownReduction=2
BloodforgeReinforceExtraDurability=0.3
BloodforgeReinforceResourceCostMultiplier=3
BloodforgeReinforceSpeedMultiplier=0.1
OutpostSigilRewardMultiplier=1

[/Script/Engine.GameSession]
MaxPlayers=8

