;METADATA=(Diff=true, UseCommands=true)
[/Script/ShooterGame.ShooterGameMode]
BabyImprintingStatScaleMultiplier=1.3
BabyCuddleIntervalMultiplier=0.5
BabyCuddleGracePeriodMultiplier=1.0
BabyCuddleLoseImprintQualitySpeedMultiplier=1.0
PerLevelStatsMultiplier_DinoTamed[0]=1.0
PerLevelStatsMultiplier_DinoTamed[1]=1.3
PerLevelStatsMultiplier_DinoTamed[2]=1.0
PerLevelStatsMultiplier_DinoTamed[3]=1.3
PerLevelStatsMultiplier_DinoTamed[4]=1.3
PerLevelStatsMultiplier_DinoTamed[5]=1.0
PerLevelStatsMultiplier_DinoTamed[6]=1.0
PerLevelStatsMultiplier_DinoTamed[7]=1.3
PerLevelStatsMultiplier_DinoTamed[8]=1.0
PerLevelStatsMultiplier_DinoTamed[9]=1.3
PerLevelStatsMultiplier_DinoTamed[10]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[0]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[1]=1.3
PerLevelStatsMultiplier_DinoTamed_Add[2]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[3]=1.3
PerLevelStatsMultiplier_DinoTamed_Add[4]=1.3
PerLevelStatsMultiplier_DinoTamed_Add[5]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[6]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[7]=1.3
PerLevelStatsMultiplier_DinoTamed_Add[8]=1.4
PerLevelStatsMultiplier_DinoTamed_Add[9]=1.3
PerLevelStatsMultiplier_DinoTamed_Add[10]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[0]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[1]=1.3
PerLevelStatsMultiplier_DinoTamed_Affinity[2]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[3]=1.3
PerLevelStatsMultiplier_DinoTamed_Affinity[4]=1.3
PerLevelStatsMultiplier_DinoTamed_Affinity[5]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[6]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[7]=1.3
PerLevelStatsMultiplier_DinoTamed_Affinity[8]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[9]=1.3
PerLevelStatsMultiplier_DinoTamed_Affinity[10]=1.0
PerLevelStatsMultiplier_DinoWild[0]=1.0
PerLevelStatsMultiplier_DinoWild[1]=1.0
PerLevelStatsMultiplier_DinoWild[2]=0.3
PerLevelStatsMultiplier_DinoWild[3]=1.0
PerLevelStatsMultiplier_DinoWild[4]=1.0
PerLevelStatsMultiplier_DinoWild[5]=1.0
PerLevelStatsMultiplier_DinoWild[6]=1.0
PerLevelStatsMultiplier_DinoWild[7]=1.0
PerLevelStatsMultiplier_DinoWild[8]=1.0
PerLevelStatsMultiplier_DinoWild[9]=1.0
PerLevelStatsMultiplier_DinoWild[10]=1.0
PerLevelStatsMultiplier_Player[0]=1.3
PerLevelStatsMultiplier_Player[1]=1.3
PerLevelStatsMultiplier_Player[2]=1.3
PerLevelStatsMultiplier_Player[3]=1.3
PerLevelStatsMultiplier_Player[4]=1.3
PerLevelStatsMultiplier_Player[5]=1.3
PerLevelStatsMultiplier_Player[6]=1.3
PerLevelStatsMultiplier_Player[7]=1.3
PerLevelStatsMultiplier_Player[8]=1.3
PerLevelStatsMultiplier_Player[9]=1.3
PerLevelStatsMultiplier_Player[10]=1.3
GlobalSpoilingTimeMultiplier=0
GlobalItemDecompositionTimeMultiplier=0
GlobalCorpseDecompositionTimeMultiplier=1
PvPZoneStructureDamageMultiplier=6
StructureDamageRepairCooldown=1.0
IncreasePvPRespawnIntervalCheckPeriod=300.0
IncreasePvPRespawnIntervalMultiplier=1.3
IncreasePvPRespawnIntervalBaseAmount=60.0
ResourceNoReplenishRadiusPlayers=1.0
ResourceNoReplenishRadiusStructures=1.0
CropGrowthSpeedMultiplier=1.8
LayEggIntervalMultiplier=1.8
PoopIntervalMultiplier=1.0
CropDecaySpeedMultiplier=1.0
MatingIntervalMultiplier=0.1
EggHatchSpeedMultiplier=20
BabyMatureSpeedMultiplier=60
BabyFoodConsumptionSpeedMultiplier=1.3
DinoTurretDamageMultiplier=1.0
DinoHarvestingDamageMultiplier=3.2
PlayerHarvestingDamageMultiplier=4.1
CustomRecipeEffectivenessMultiplier=1.3
CustomRecipeSkillMultiplier=1.3
AutoPvEStartTimeSeconds=0
AutoPvEStopTimeSeconds=0
KillXPMultiplier=1.3
HarvestXPMultiplier=1.3
CraftXPMultiplier=1.3
GenericXPMultiplier=1.3
SpecialXPMultiplier=1.3
FuelConsumptionIntervalMultiplier=4.0
PhotoModeRangeLimit=3000
bDisablePhotoMode=False
bIncreasePvPRespawnInterval=True
bAutoPvETimer=False
bAutoPvEUseSystemTime=False
bDisableFriendlyFire=True
bFlyerPlatformAllowUnalignedDinoBasing=False
bDisableLootCrates=False
bAllowCustomRecipes=True
bPassiveDefensesDamageRiderlessDinos=True
bPvEAllowTribeWar=True
bPvEAllowTribeWarCancel=True
MaxDifficulty=True
bUseSingleplayerSettings=False
bUseCorpseLocator=True
bShowCreativeMode=True
bHardLimitTurretsInRange=True
bDisableStructurePlacementCollision=True
bAllowPlatformSaddleMultiFloors=False
bAllowUnlimitedRespecs=True
bDisableDinoRiding=False
bDisableDinoTaming=False
OverrideMaxExperiencePointsPlayer=0
OverrideMaxExperiencePointsDino=0
MaxNumberOfPlayersInTribe=0
ExplorerNoteXPMultiplier=1.0
BossKillXPMultiplier=1.0
AlphaKillXPMultiplier=1.0
WildKillXPMultiplier=1.0
CaveKillXPMultiplier=1.0
TamedKillXPMultiplier=1.0
UnclaimedKillXPMultiplier=1.0
SupplyCrateLootQualityMultiplier=2
FishingLootQualityMultiplier=2
CraftingSkillBonusMultiplier=3
bDisableDefaultDinoTaming=False
bAllowSpeedLeveling=True
bAllowFlyerSpeedLeveling=True

[/Script/ShooterGame.ShooterPlayerController_Menu]
DiscordAccessToken=YourAccessTokenHere
DiscordRefreshToken=YourRefreshTokenHere

[ShooterGameMode_TEMPOverrides]
bUseCorpseLocator=True

